---
# file: wordpress/tasks/dir_setup.yml


      
- name: Create directory structure
  file: >
    path={{ wordpress_site_dir_www_root }}/{{ wordpress_site_name }}{{ item.value.path }}
    owner={{ wordpress_site_user_www }}
    group={{ wordpress_site_group_www }}
    mode={{ wordpress_site_dir_mode }}
    state=directory
  with_dict: wordpress_dir_structure
  
#- name: Copy application files to server
#  copy: >
#    src={{ item.src }} 
#    dest={{ wordpress_site_dir_www_root }}/{{ wordpress_site_name }}{{ item.dest }}
#  with_items:
#    - src: 'public_index.php'
#      dest: '/public/index.php'
#    - src: 'public_wp-config.php'
#      dest: '/public/wp-config.php'
#    - src: 'wp-cli.yml'
#      dest: '/wp-cli.yml'
#    - src: 'muplugin_register-theme-directory.php'
#      dest: '/public/app/mu-plugins/regsiter-theme-directory.php'
#    - src: 'muplugin_disallow-indexing.php'
#      dest: '/public/app/mu-plugins/disallow-indexing.php'
#    - src: 'muplugin_bedrock-autoloader.php'
#      dest: '/public/app/mu-plugins/bedrock-autoloader.php'
#    - src: 'config_application.php'
#      dest: '/config/application.php'
#  tags:
#    - wordpress
        


    