---
# file: wordpress/tasks/database.yml

- name: Create database for each site
  mysql_db: >
    name={{ wordpress_site_db_name }}
    state=present
    login_host={{ wordpress_site_db_host }}
  register: wordpress_db_created

- name: Copy saved database to server
  copy: >
    src={{ wordpress_site_name }}.sql
    dest=/tmp/{{ wordpress_site_name }}.sql
  when: wordpress_site_restore_saved_db

- name: Import saved database
  mysql_db: >
    name={{ wordpress_site_db_name }}
    state=import
    target=/tmp/{{ wordpress_site_name }}.sql
    login_host={{ wordpress_site_db_host }}
  when: wordpress_site_restore_saved_db

- name: Create/assign database user to db and grant permissions
  mysql_user: >
    name={{ wordpress_site_db_user }}
    password={{ wordpress_site_db_password }}
    priv='{{ wordpress_site_db_name }}.*:ALL'
    state=present
    login_host={{ wordpress_site_db_host }}
