---
# file: wordpress/tasks/dir_setup.yml

- name: Create directory structure
  file: >
    path={{ wordpress_site_dir_www_root }}/{{ wordpress_site_name }}{{ item.value.path }}
    owner={{ wordpress_site_user_www }}
    group={{ wordpress_site_group_www }}
    mode={{ wordpress_site_dir_mode }}
    state=directory
  with_dict: wordpress_dir_structure
  
#- name: Copy Deploy Key
#  copy: >
#    src={{ wordpress_site_repository_deploy_key }}
#    dest=~/.ssh/{{ wordpress_site_name }}_deploy
#    owner=root 
#    group=root 
#    mode=0600

- name: Checkout site files
  git: >
    repo={{ wordpress_site_repository }}
    dest={{ wordpress_site_dir_www_root }}/{{ wordpress_site_name }}
    accept_hostkey=true
    
    