---
# file: wordpress/tasks/dir_setup.yml

- name: Create directory structure
  file: >
    path={{ wordpress_dir_www_root }}/{{ item[0].domain }}{{ item[1] }}
    owner={{ wordpress_user_www }}
    group={{ wordpress_group_www }}
    mode={{ wordpress_dir_mode }}
    state=directory
  with_nestd:
    - wordpress_sites
    - wordpress_dir_structure
