---
# file: wordpress/tasks/files.yml

- name: Copy static files
  copy: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ wordpress_user_www }}
    group={{ wordpress_group_www }}
    mode={{ wordpress_file_mode }}
  with_items:
        - { src: 'application.php',                    dest: '/etc/nginx/nginx.conf' }
        - { src: 'index.php',                    dest: '/etc/nginx/mime.types' }
        - { src: 'fastcgi_params',                dest: '/etc/nginx/fastcgi_params' }
        - { src: 'sites-available/default',       dest: '/etc/nginx/sites-available/default' }
        - { src: 'conf.d/common.conf',            dest: '/etc/nginx/conf.d/common.conf' }
        - { src: 'conf.d/hide-headers.conf',      dest: '/etc/nginx/conf.d/hide-headers.conf' }

- name: Generate other files
  copy: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ wordpress_user_www }}
    group={{ wordpress_group_www }}
    mode={{ wordpress_file_mode }}
  with_items:
        - { src: 'nginx.conf',                    dest: '/etc/nginx/nginx.conf' }
        - { src: 'mime.types',                    dest: '/etc/nginx/mime.types' }
        - { src: 'fastcgi_params',                dest: '/etc/nginx/fastcgi_params' }
        - { src: 'sites-available/default',       dest: '/etc/nginx/sites-available/default' }
        - { src: 'conf.d/common.conf',            dest: '/etc/nginx/conf.d/common.conf' }
        - { src: 'conf.d/hide-headers.conf',      dest: '/etc/nginx/conf.d/hide-headers.conf' }
