---
# file: wordpress/tasks/main.yml

- include: database.yml
- include: dir_setup.yml
- include: nginx.yml

- name: Install Dependencies with Composer
  composer: >
    working_dir='{{ wordpress_site_dir_www_root }}/{{ wordpress_site_name }}'
  when: wordpress_site_run_composer

- name: WP installed?
  command: >
    wp core is-installed
    --allow-root chdir={{ wordpress_site_dir_www_root }}/{{ wordpress_site_name }}
  register: wordpress_site_status
  ignore_errors: True

- name: Install WP
  command: >
    wp core install
    --allow-root
    --url='{{ wordpress_site_home }}'
    --title='{{ wordpress_site_title }}'
    --admin_user='{{ wordpress_site_admin_user }}'
    --admin_password='{{ wordpress_site_admin_password }}'
    --admin_email='{{ wordpress_site_admin_email }}'
  args:
    chdir: "{{ wordpress_dir_www_root }}/{{ wordpress_site_name }}/"
  when: wordpress_site_status.rc == 1 and wordpress_site_install == True and wordpress_site_multisite_enabled == False
  notify: reload nginx

- name: Install WP Multisite
  command: >
    wp core multisite-install
    --allow-root
    --url='{{ wordpress_site_home  }}'
    --base='{{ iwordpress_site_multisite_base_path }}'
    --subdomains='{{ wordpress_site_multisite_subdomains }}'
    --title='{{ wordpress_site_site_title }}'
    --admin_user='{{ wordpress_site_admin_user }}'
    --admin_password='{{ wordpress_site_admin_password }}'
    --admin_email='{{ wordpress_site_admin_email }}'
  args:
    chdir: "{{ wordpress_site_dir_www_root }}/{{ wordpress_site_name }}/current/"
  when: wordpress_site_status.rc == 1 and wordpress_site_install == True and wordpress_site_multisite_enabled == True
  notify: Reload Nginx

- name: Setup system cron
  cron: >
    name='{{ wordpress_site_name }} WordPress cron'
    minute='*/15'
    user='{{ wordpress_site_user_www }}'
    job='curl -s {{ wordpress_site_home }}/wp-cron.php'
    cron_file='wordpress_{{ wordpress_site_name }}'
  when: wordpress_site_system_cron
