---
# file: wordpress/tasks/main.yml

- include: database.yml
- include: dir_setup.yml
- include: nginx.yml

- name: Install Dependencies with Composer
  composer: >
    install
    working_dir={{ wordpress_dir_www_root }}/{{ item.domain }}
  with_items: wordpress_sites
  when: item.run_composer|default(False) == True

- name: WP installed?
  command: >
    wp core is-installed
    --allow-root chdir={{ wordpress_dir_www_root }}/{{ item.domain }}
  register: site_statuses
  ignore_errors: True
  with_items: wordpress_sites

- name: Install WP
  command: >
    wp core install
    --allow-root
    --url='{{ item.item.home | default("http://"+item.item.domain) }}'
    --title='{{ item.item.site_title | default("") }}'
    --admin_user='{{ item.item.admin_user }}'
    --admin_password='{{ item.item.admin_password }}'
    --admin_email='{{ item.item.admin_email }}'
  args:
    chdir: "{{ wordpress_dir_www_root }}/{{ item.item.site_name }}/"
  with_items: site_statuses.results
  when: item.rc == 1 and item.item.site_install == True and item.item.multisite.enabled|default(False) == False
  notify: reload nginx

- name: Install WP Multisite
  command: >
    wp core multisite-install
    --allow-root
    --url='{{ item.item.home | default("http://"+item.item.domain) }}'
    --base='{{ item.item.multisite.base_path | default('/') }}'
    --subdomains='{{ item.item.multisite.subdomains | default('false') }}'
    --title='{{ item.item.site_title | default(item.item.site_name) }}'
    --admin_user='{{ item.item.admin_user }}'
    --admin_password='{{ item.item.admin_password }}'
    --admin_email='{{ item.item.admin_email }}'
  args:
    chdir: "{{ wordpress_dir_www_root }}/{{ item.item.site_name }}/current/"
  with_items: site_statuses.results
  when: item.rc == 1 and item.item.site_install == True and item.item.multisite.enabled|default(False) == True
  notify: reload nginx

- name: Setup system cron
  cron: >
    name='{{ item.domain }} WordPress cron'
    minute='*/15'
    user={{ wordpress_user_www }}
    job='curl -s {{ item.home | default("http://"+item.domain) }}/wp-cron.php'
    cron_file=wordpress_{{ item.domain }}
  with_items: wordpress_sites
  when: item.system_cron|default(False) == True
