---
# file: wordpress/tasks/main.yml
- name: Backup Wordpress
  include: backup.yml
  tags:
    - wordpress
    - wordpress_backup
    
- name: Setup Base Directories
  include: directories.yml
  tags:
    - wordpress
    - wordpress_directories
    
- name: Create or Restore Site Database
  include: database.yml
  tags:
    - wordpress
    - wordpress_database

- name: Deploy Site Source Files
  include: deploy.yml
  tags:
    - wordpress
    - wordpress_deploy


- name: Install or Update Wordpress
  include: install.yml
  tags: 
    - wordpress
    - wordpress_install
    
- name: Install or Update Wordpress Plugins
  include: plugins.yml
  tags:
    - wordpress
    - wordpress_plugins
    
- name: Configure Site with Nginx
  inlude: nginx.yml
  tags:
    - wordpress
    - wordpress_nginx

- name: Configure System Settings
  include: system.yml
  tags:
    - wordpress
    - wordpress_system




