---
# file: wordpress/tasks/nginx.yml

- name: Create Nginx configuration for Wordpress site
  template: >
    src=wordpress-site.conf
    dest={{ nginx_root }}/sites-available/{{ wordpress_site_name }}

- name: Enable WordPress site
  file: >
    src={{ nginx_root }}/sites-available/{{ wordpress_site_name }}
    dest={{ nginx_root }}/sites-enabled/{{ wordpress_site_name }}
    state=link
  notify: Reload Nginx

- name: Create Php-FPM configuration
  template: >
    src=php-fpm.conf
    dest={{ php_dir_pool }}/{{ wordpress_site_name }}.conf
  notify: Restart Php5-fpm
