- name: Reload Nginx
  service: name=nginx state=reloaded enabled=yes
- name: Restart Php5-fpm
  service: name=php5-fpm state=restarted enabled=yes
- name: Newaliases
  command: newaliases
  
- name: Open HTTP Ports
  ufw: rule=allow name='Nginx HTTP'
  when: not ufw_override_web
  
- name: Open HTTPS Ports
  ufw: rule=allow name='Nginx HTTPS'
  when: not ufw_override_web
